#配置数据源
spring:
  datasource:
    username: root     #数据库用户名
    password: 237735001aS   #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库连接驱动
    url: jdbc:mysql://localhost:3306/cgshop_database1   #数据库连接字符串
  servlet:
    multipart:
      max-file-size: 10485760 #默认大小10m
#配置日志级别 输入sql语句
logging:
  level:
    com.by.mapper: debug  #mapper层debue级别 输入sql语句

server:
  port: 8081

